# Cargo audit configuration
# https://rustsec.org/

[advisories]
# Advisories to ignore
ignore = [
    # RUSTSEC-2023-0071: rsa - Marvin Attack
    # This vulnerability is in sqlx-mysql which is pulled in by sqlx-macros-core
    # even when only using postgres. We don't use MySQL authentication.
    # See: https://github.com/launchbadge/sqlx/issues/3538
    "RUSTSEC-2023-0071",

    # RUSTSEC-2025-0134: rustls-pemfile unmaintained
    # This is pulled in by testcontainers via bollard (dev dependency only)
    # Not a security vulnerability, just a maintenance warning
    "RUSTSEC-2025-0134",
]
